### ISSUE TITLE
Support for linux/arm/v7

### ISSUE THREAD

**Issue by m04ndj5xc2u3pn4eow** [PussTheCat-org/docker-bibliogram-quay#1]
I am inquiring if it's possible for this docker image to support `linux/arm/v7` architecture?

Thank you!

**Comment by TheFrenchGhosty** [comment]
It sadly isn't just as simple as enabling it... so... maybe later? https://github.com/PussTheCat-org/docker-bibliogram-quay/runs/5504150311?check_suite_focus=true#step:6:1635

**Comment by m04ndj5xc2u3pn4eow** [comment]
Ah, no worries. Thanks for quick response!
